backend:
  name: github
  repo: griscalgaro/griscalgaro.github.io
  branch: master
  api_root: https://api.github.com
  base_url: https://api.netlify.com
  auth_endpoint: auth
  
publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}